general:
  statefile: "state.gob"
feeds:
  - name: "feed1"
    url: "https://example.com/feed1.xml"
    interval: 60
    max_items: 10
    filters:
      - type: "title"
        pattern: ".*"
      - type: "description"
        pattern: ".*"
  - name: "feed2"
    url: "https://example.com/feed2.xml"
    interval: 60
    max_items: 10
    filters:
      - type: "title"
        pattern: ".*"
      - type: "description"
        pattern: ".*"